jobs:
  cleanup:
    if: ${{ github.event_name == 'workflow_dispatch' || ( github.ref == 'refs/heads/main'
      && !(contains(github.event, 'head_commit') || github.event.head_commit.message
      == 'Initial commit' )) }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Remove Helper Files
      run: "rm -rf \\\n  .github/workflows/cleanup-on-create.yaml \\\n  CHANGELOG.md\n"
    - name: Initialize README
      run: 'sed -i.bak "s/{repo}/$(basename ${{ github.repository }})/g" README.md

        sed -i.bak "s/{owner}/$(dirname ${{ github.repository }})/g" README.md

        '
    - name: Initialize Pull Request Template
      run: 'sed -i.bak "s/{repo}/$(basename ${{ github.repository }})/g" .github/pull_request_template.md

        sed -i.bak "s/{owner}/$(dirname ${{ github.repository }})/g" .github/pull_request_template.md

        '
    - name: Commit changes
      run: 'git config --local user.email "helix@adobe.com"

        git config --local user.name "AEM Bot"

        git add .

        git commit -m "chore: cleanup repository template"

        git push

        '
'on':
- workflow_dispatch
permissions: write-all
